runtime: nodejs14 # especifica la versión de Node.js

instance_class: F2 # especifica la clase de instancia

automatic_scaling: # configura el escalado automático
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables: # define las variables de entorno
  NODE_ENV: "production"

entrypoint: # especifica el comando para iniciar tu aplicación
  npm start